/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 30 17:38:17 GMT 2026
 */

package org.apache.zookeeper.server.watch;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.CharArrayWriter;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Stack;
import org.apache.zookeeper.Watcher;
import org.apache.zookeeper.data.ACL;
import org.apache.zookeeper.server.watch.WatchManager_ESTest_scaffolding;
import org.apache.zookeeper.server.DumbWatcher;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockPrintWriter;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class WatchManager_ESTest extends WatchManager_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      boolean boolean0 = watchManager0.addWatch("o", (Watcher) null);
      assertTrue(boolean0);
      
      WatchesSummary watchesSummary0 = watchManager0.getWatchesSummary();
      assertEquals(1, watchesSummary0.getTotalWatches());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      WatcherMode watcherMode0 = WatcherMode.STANDARD;
      watchManager0.addWatch("; \"{S", (Watcher) dumbWatcher0, watcherMode0);
      WatchesPathReport watchesPathReport0 = watchManager0.getWatchesByPath();
      assertNotNull(watchesPathReport0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      WatcherMode watcherMode0 = WatcherMode.STANDARD;
      watchManager0.addWatch("; \"{S", (Watcher) dumbWatcher0, watcherMode0);
      WatchesReport watchesReport0 = watchManager0.getWatches();
      assertNotNull(watchesReport0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
      boolean boolean0 = watchManager0.addWatch(";V", (Watcher) dumbWatcher0, watcherMode0);
      WatcherMode watcherMode1 = WatcherMode.STANDARD;
      boolean boolean1 = watchManager0.removeWatcher(";V", (Watcher) dumbWatcher0, watcherMode1);
      assertFalse(boolean1 == boolean0);
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      WatcherMode watcherMode0 = WatcherMode.STANDARD;
      boolean boolean0 = watchManager0.addWatch("q>/`L@nGJ30;", (Watcher) dumbWatcher0, watcherMode0);
      watchManager0.addWatch("7Odhp+lGi?q#q2%9", (Watcher) null);
      boolean boolean1 = watchManager0.removeWatcher("7Odhp+lGi?q#q2%9", (Watcher) dumbWatcher0, watcherMode0);
      assertFalse(boolean1 == boolean0);
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
      watchManager0.addWatch(";V", (Watcher) dumbWatcher0, watcherMode0);
      boolean boolean0 = watchManager0.addWatch(";V", (Watcher) dumbWatcher0);
      assertTrue(boolean0);
      
      boolean boolean1 = watchManager0.removeWatcher(";V", (Watcher) dumbWatcher0, watcherMode0);
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
      boolean boolean0 = watchManager0.addWatch("inconsistent watch table for watcher {}, {} not in path list", (Watcher) dumbWatcher0, watcherMode0);
      assertTrue(boolean0);
      
      boolean boolean1 = watchManager0.removeWatcher("inconsistent watch table for watcher {}, {} not in path list", (Watcher) dumbWatcher0);
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      boolean boolean0 = watchManager0.addWatch("", (Watcher) null);
      boolean boolean1 = watchManager0.removeWatcher("1 connections watching 1 paths\nTotal watches:1", (Watcher) null);
      assertFalse(boolean1 == boolean0);
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      watchManager0.addWatch("", (Watcher) null);
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
      boolean boolean0 = watchManager0.addWatch("", (Watcher) dumbWatcher0, watcherMode0);
      assertTrue(boolean0);
      
      boolean boolean1 = watchManager0.removeWatcher("", (Watcher) dumbWatcher0, watcherMode0);
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      watchManager0.addWatch("PjC#@X42:^4QC'h(Hw/", (Watcher) dumbWatcher0);
      boolean boolean0 = watchManager0.addWatch("qIn`Cjo'R{]<Z", (Watcher) dumbWatcher0);
      assertTrue(boolean0);
      
      WatcherMode watcherMode0 = WatcherMode.STANDARD;
      boolean boolean1 = watchManager0.removeWatcher("PjC#@X42:^4QC'h(Hw/", (Watcher) dumbWatcher0, watcherMode0);
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      WatcherMode watcherMode0 = WatcherMode.PERSISTENT;
      boolean boolean0 = watchManager0.addWatch("org.eclipse.jetty.util.PathWatcher$PathWatchEventType", (Watcher) dumbWatcher0, watcherMode0);
      assertTrue(boolean0);
      
      boolean boolean1 = watchManager0.containsWatcher("org.eclipse.jetty.util.PathWatcher$PathWatchEventType", (Watcher) dumbWatcher0, watcherMode0);
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      boolean boolean0 = watchManager0.addWatch("", (Watcher) null);
      assertTrue(boolean0);
      
      boolean boolean1 = watchManager0.containsWatcher("", (Watcher) null);
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      boolean boolean0 = watchManager0.addWatch("o", (Watcher) null);
      WatcherMode watcherMode0 = WatcherMode.PERSISTENT;
      boolean boolean1 = watchManager0.containsWatcher("o", (Watcher) null, watcherMode0);
      assertFalse(boolean1 == boolean0);
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
      boolean boolean0 = watchManager0.addWatch(";V", (Watcher) dumbWatcher0, watcherMode0);
      boolean boolean1 = watchManager0.containsWatcher("9+h_+%6-_&Gk's", (Watcher) dumbWatcher0);
      assertFalse(boolean1 == boolean0);
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      DumbWatcher dumbWatcher0 = new DumbWatcher(64L);
      WatcherMode watcherMode0 = WatcherMode.PERSISTENT;
      watchManager0.addWatch("", (Watcher) dumbWatcher0, watcherMode0);
      CharArrayWriter charArrayWriter0 = new CharArrayWriter();
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(charArrayWriter0, true);
      watchManager0.dumpWatches(mockPrintWriter0, false);
      assertEquals(9, charArrayWriter0.size());
      assertEquals("0x40\r\n\t\r\n", charArrayWriter0.toString());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      DumbWatcher dumbWatcher0 = new DumbWatcher(64L);
      WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
      watchManager0.addWatch("=9", (Watcher) dumbWatcher0, watcherMode0);
      CharArrayWriter charArrayWriter0 = new CharArrayWriter();
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(charArrayWriter0, true);
      watchManager0.dumpWatches(mockPrintWriter0, true);
      assertEquals(10, charArrayWriter0.size());
      assertEquals("=9\r\n\t0x40\n", charArrayWriter0.toString());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      boolean boolean0 = watchManager0.addWatch("", (Watcher) null);
      assertTrue(boolean0);
      
      String string0 = watchManager0.toString();
      assertEquals("1 connections watching 1 paths\nTotal watches:1", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      watchManager0.addWatch("PjC#@X2:^4QC'h(Hw/", (Watcher) dumbWatcher0);
      Stack<ACL> stack0 = new Stack<ACL>();
      Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.NodeChildrenChanged;
      WatcherOrBitSet watcherOrBitSet0 = watchManager0.triggerWatch("PjC#@X2:^4QC'h(Hw/", watcher_Event_EventType0, 0L, (List<ACL>) stack0);
      assertEquals(1, watcherOrBitSet0.size());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      watchManager0.addWatch("PjC#@X2:^4QC'h(Hw/", (Watcher) dumbWatcher0);
      Stack<ACL> stack0 = new Stack<ACL>();
      Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.NodeDataChanged;
      WatcherOrBitSet watcherOrBitSet0 = watchManager0.triggerWatch("PjC#@X2:^4QC'h(Hw/", watcher_Event_EventType0, 67108841L, (List<ACL>) stack0);
      assertEquals(1, watcherOrBitSet0.size());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      watchManager0.addWatch("PjC#@X2:^4QC'h(Hw/", (Watcher) dumbWatcher0);
      Stack<ACL> stack0 = new Stack<ACL>();
      Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.NodeCreated;
      WatcherOrBitSet watcherOrBitSet0 = watchManager0.triggerWatch("PjC#@X2:^4QC'h(Hw/", watcher_Event_EventType0, 0L, (List<ACL>) stack0);
      assertEquals(1, watcherOrBitSet0.size());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      watchManager0.addWatch("PjC#@X2:^4QC'h(Hw/", (Watcher) null);
      Stack<ACL> stack0 = new Stack<ACL>();
      Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.PersistentWatchRemoved;
      // Undeclared exception!
      try { 
        watchManager0.triggerWatch("PjC#@X2:^4QC'h(Hw/", watcher_Event_EventType0, 69L, (List<ACL>) stack0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.server.watch.WatchManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      watchManager0.addWatch("PjC#@X2:^4QC'h(Hw/", (Watcher) dumbWatcher0);
      Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.NodeDeleted;
      Stack<ACL> stack0 = new Stack<ACL>();
      LinkedHashSet<Watcher> linkedHashSet0 = new LinkedHashSet<Watcher>();
      WatcherOrBitSet watcherOrBitSet0 = new WatcherOrBitSet(linkedHashSet0);
      linkedHashSet0.add(dumbWatcher0);
      WatcherOrBitSet watcherOrBitSet1 = watchManager0.triggerWatch("PjC#@X2:^4QC'h(Hw/", watcher_Event_EventType0, 1704L, (List<ACL>) stack0, watcherOrBitSet0);
      assertEquals(1, watcherOrBitSet1.size());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      watchManager0.addWatch("PjC#@X2:^4QC'h(Hw/", (Watcher) dumbWatcher0);
      Stack<ACL> stack0 = new Stack<ACL>();
      Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.DataWatchRemoved;
      WatcherOrBitSet watcherOrBitSet0 = watchManager0.triggerWatch("PjC#@X2:^4QC'h(Hw/", watcher_Event_EventType0, (-1L), (List<ACL>) stack0);
      assertEquals(1, watcherOrBitSet0.size());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
      watchManager0.addWatch("q>/`r@nGJ30;", (Watcher) dumbWatcher0, watcherMode0);
      Stack<ACL> stack0 = new Stack<ACL>();
      Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.None;
      // Undeclared exception!
      try { 
        watchManager0.triggerWatch("q>/`r@nGJ30;", watcher_Event_EventType0, (long) 0, (List<ACL>) stack0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      watchManager0.addWatch("PjC#@X2:^4QC'h(Hw/", (Watcher) dumbWatcher0);
      Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.NodeDeleted;
      Stack<ACL> stack0 = new Stack<ACL>();
      LinkedHashSet<Watcher> linkedHashSet0 = new LinkedHashSet<Watcher>();
      WatcherOrBitSet watcherOrBitSet0 = new WatcherOrBitSet(linkedHashSet0);
      WatcherOrBitSet watcherOrBitSet1 = watchManager0.triggerWatch("PjC#@X2:^4QC'h(Hw/", watcher_Event_EventType0, (-65536L), (List<ACL>) stack0, watcherOrBitSet0);
      assertEquals(1, watcherOrBitSet1.size());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
      watchManager0.addWatch("VU+`p)F!-al~D;`", (Watcher) dumbWatcher0, watcherMode0);
      watchManager0.removeWatcher((Watcher) dumbWatcher0);
      assertEquals(0L, dumbWatcher0.getLastLatency());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      watchManager0.addWatch("PjC#@X2:^4QC'h(Hw/", (Watcher) dumbWatcher0);
      DumbWatcher dumbWatcher1 = new DumbWatcher();
      watchManager0.addWatch("PjC#@X2:^4QC'h(Hw/", (Watcher) dumbWatcher1);
      watchManager0.removeWatcher((Watcher) dumbWatcher0);
      assertEquals(0L, dumbWatcher0.getOutstandingRequests());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      watchManager0.removeWatcher((Watcher) dumbWatcher0);
      assertFalse(dumbWatcher0.isSecure());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
      watchManager0.addWatch("q>/`r@nGJ30;", (Watcher) dumbWatcher0, watcherMode0);
      watchManager0.addWatch("q>/`r@nGJ30;", (Watcher) dumbWatcher0);
      Stack<ACL> stack0 = new Stack<ACL>();
      Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.None;
      // Undeclared exception!
      try { 
        watchManager0.triggerWatch("q>/`r@nGJ30;", watcher_Event_EventType0, (long) 0, (List<ACL>) stack0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      dumbWatcher0.setStale();
      boolean boolean0 = watchManager0.addWatch("acls", (Watcher) dumbWatcher0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      boolean boolean0 = watchManager0.addWatch("", (Watcher) null);
      assertTrue(boolean0);
      
      int int0 = watchManager0.size();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      boolean boolean0 = watchManager0.removeWatcher("inconsistent watch table for watcher {}, {} not in path list", (Watcher) dumbWatcher0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      Stack<ACL> stack0 = new Stack<ACL>();
      Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.DataWatchRemoved;
      WatcherOrBitSet watcherOrBitSet0 = watchManager0.triggerWatch("PjC#@X2:^4QC'h(Hw/", watcher_Event_EventType0, (-1L), (List<ACL>) stack0);
      assertNull(watcherOrBitSet0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      Map<Watcher, Map<String, WatchStats>> map0 = watchManager0.getWatch2Paths();
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      boolean boolean0 = watchManager0.addWatch("PjC#@X2:^4QC'h(Hw/", (Watcher) dumbWatcher0);
      boolean boolean1 = watchManager0.addWatch("PjC#@X2:^4QC'h(Hw/", (Watcher) dumbWatcher0);
      assertFalse(boolean1 == boolean0);
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      watchManager0.shutdown();
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      WatchManager watchManager0 = new WatchManager();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      boolean boolean0 = watchManager0.containsWatcher("9+h_+%6-_&Gk's", (Watcher) dumbWatcher0);
      assertFalse(boolean0);
  }
}
