/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 01 15:51:43 GMT 2026
 */

package org.apache.zookeeper.server.watch.watchmanager.variant_c4.evosuite;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.ByteArrayOutputStream;
import java.io.CharArrayWriter;
import java.io.PrintWriter;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import org.apache.zookeeper.Watcher;
import org.apache.zookeeper.data.ACL;
import org.apache.zookeeper.server.DumbWatcher;
import org.apache.zookeeper.server.watch.WatchManager;
import org.apache.zookeeper.server.watch.WatchStats;
import org.apache.zookeeper.server.watch.WatcherMode;
import org.apache.zookeeper.server.watch.WatcherOrBitSet;
import org.apache.zookeeper.server.watch.WatchesPathReport;
import org.apache.zookeeper.server.watch.WatchesReport;
import org.apache.zookeeper.server.watch.WatchesSummary;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class WatchManager_ESTest extends WatchManager_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test00()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
        watchManager0.addWatch("M52p/'J.YZ'", (Watcher) null, watcherMode0);
        LinkedList<ACL> linkedList0 = new LinkedList<ACL>();
        Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.NodeDeleted;
        // Undeclared exception!
        try {
            watchManager0.triggerWatch("M52p/'J.YZ'", watcher_Event_EventType0, 1L, (List<ACL>) linkedList0);
            fail("Expecting exception: StringIndexOutOfBoundsException");

        } catch(StringIndexOutOfBoundsException e) {
        }
    }

    @Test(timeout = 4000)
    public void test01()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT;
        boolean boolean0 = watchManager0.addWatch("M52p/'J.YZ'", (Watcher) null, watcherMode0);
        assertTrue(boolean0);

        WatchesSummary watchesSummary0 = watchManager0.getWatchesSummary();
        assertEquals(1, watchesSummary0.getTotalWatches());
    }

    @Test(timeout = 4000)
    public void test02()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        WatcherMode watcherMode0 = WatcherMode.STANDARD;
        watchManager0.addWatch("org.eclipse.jetty.server.ServerConnector", (Watcher) dumbWatcher0, watcherMode0);
        WatchesPathReport watchesPathReport0 = watchManager0.getWatchesByPath();
        assertNotNull(watchesPathReport0);
    }

    @Test(timeout = 4000)
    public void test03()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher(1082L);
        watchManager0.addWatch("t3A,", (Watcher) dumbWatcher0);
        WatchesReport watchesReport0 = watchManager0.getWatches();
        assertNotNull(watchesReport0);
    }

    @Test(timeout = 4000)
    public void test04()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT;
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        boolean boolean0 = watchManager0.addWatch("9M52p/'J.YZ'", (Watcher) dumbWatcher0, watcherMode0);
        assertTrue(boolean0);

        watchManager0.addWatch("9M52p/'J.YZ'", (Watcher) null, watcherMode0);
        boolean boolean1 = watchManager0.removeWatcher("9M52p/'J.YZ'", (Watcher) null);
        assertTrue(boolean1);
    }

    @Test(timeout = 4000)
    public void test05()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        watchManager0.addWatch("=M)2p/2J.PZ'", (Watcher) null);
        boolean boolean0 = watchManager0.addWatch("\t0x", (Watcher) null);
        assertTrue(boolean0);

        boolean boolean1 = watchManager0.removeWatcher("=M)2p/2J.PZ'", (Watcher) null);
        assertTrue(boolean1);
    }

    @Test(timeout = 4000)
    public void test06()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        watchManager0.addWatch("M52p/'J.YZ'", (Watcher) null);
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT;
        boolean boolean0 = watchManager0.addWatch("M52p/'J.YZ'", (Watcher) null, watcherMode0);
        assertTrue(boolean0);

        boolean boolean1 = watchManager0.removeWatcher("M52p/'J.YZ'", (Watcher) null, watcherMode0);
        assertTrue(boolean1);
    }

    @Test(timeout = 4000)
    public void test07()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
        boolean boolean0 = watchManager0.addWatch("d<L,uSFHat>Ak}#4", (Watcher) null);
        boolean boolean1 = watchManager0.removeWatcher("d<L,uSFHat>Ak}#4", (Watcher) null, watcherMode0);
        assertFalse(boolean1 == boolean0);
        assertFalse(boolean1);
    }

    @Test(timeout = 4000)
    public void test08()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
        boolean boolean0 = watchManager0.addWatch("", (Watcher) null, watcherMode0);
        assertTrue(boolean0);

        boolean boolean1 = watchManager0.removeWatcher("", (Watcher) null, watcherMode0);
        assertTrue(boolean1);
    }

    @Test(timeout = 4000)
    public void test09()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        watchManager0.addWatch("M52p/'J.YZ'", (Watcher) null);
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        WatcherMode watcherMode0 = WatcherMode.STANDARD;
        boolean boolean0 = watchManager0.addWatch("Xt:|s~V#FcjXYp", (Watcher) dumbWatcher0, watcherMode0);
        boolean boolean1 = watchManager0.removeWatcher("Xt:|s~V#FcjXYp", (Watcher) null, watcherMode0);
        assertFalse(boolean1 == boolean0);
        assertFalse(boolean1);
    }

    @Test(timeout = 4000)
    public void test10()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        boolean boolean0 = watchManager0.addWatch("E@gTU jjTX\"Nli1", (Watcher) null);
        boolean boolean1 = watchManager0.removeWatcher("No watchers for ", (Watcher) null);
        assertFalse(boolean1 == boolean0);
        assertFalse(boolean1);
    }

    @Test(timeout = 4000)
    public void test11()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
        boolean boolean0 = watchManager0.addWatch("", (Watcher) null, watcherMode0);
        assertTrue(boolean0);

        boolean boolean1 = watchManager0.containsWatcher("", (Watcher) null, watcherMode0);
        assertTrue(boolean1);
    }

    @Test(timeout = 4000)
    public void test12()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
        boolean boolean0 = watchManager0.addWatch("", (Watcher) null);
        boolean boolean1 = watchManager0.containsWatcher("", (Watcher) null, watcherMode0);
        assertFalse(boolean1 == boolean0);
        assertFalse(boolean1);
    }

    @Test(timeout = 4000)
    public void test13()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        WatcherMode watcherMode0 = WatcherMode.STANDARD;
        boolean boolean0 = watchManager0.addWatch("", (Watcher) null, watcherMode0);
        boolean boolean1 = watchManager0.containsWatcher("Forcing shutdown", (Watcher) null, watcherMode0);
        assertFalse(boolean1 == boolean0);
        assertFalse(boolean1);
    }

    @Test(timeout = 4000)
    public void test14()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        boolean boolean0 = watchManager0.addWatch("", (Watcher) null);
        assertTrue(boolean0);

        boolean boolean1 = watchManager0.containsWatcher("", (Watcher) null);
        assertTrue(boolean1);
    }

    @Test(timeout = 4000)
    public void test15()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher(1082L);
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
        watchManager0.addWatch("t3A,", (Watcher) dumbWatcher0, watcherMode0);
        ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream(2004);
        PrintWriter printWriter0 = new PrintWriter(byteArrayOutputStream0, true);
        watchManager0.dumpWatches(printWriter0, true);
        assertEquals("t3A,\r\n", byteArrayOutputStream0.toString());
        assertEquals(6, byteArrayOutputStream0.size());
    }

    @Test(timeout = 4000)
    public void test16()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        boolean boolean0 = watchManager0.addWatch("=M2p/2J.YZ'", (Watcher) null);
        assertTrue(boolean0);

        String string0 = watchManager0.toString();
        assertEquals("1 connections watching 1 paths\nTotal watches:1", string0);
    }

    @Test(timeout = 4000)
    public void test17()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        watchManager0.addWatch("M52p/'J.YZ'", (Watcher) null);
        LinkedList<ACL> linkedList0 = new LinkedList<ACL>();
        Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.NodeChildrenChanged;
        // Undeclared exception!
        try {
            watchManager0.triggerWatch("M52p/'J.YZ'", watcher_Event_EventType0, 10L, (List<ACL>) linkedList0);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.zookeeper.server.watch.WatchManager", e);
        }
    }

    @Test(timeout = 4000)
    public void test18()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        watchManager0.addWatch("M52p/'J.YZ'", (Watcher) null);
        LinkedList<ACL> linkedList0 = new LinkedList<ACL>();
        Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.NodeDataChanged;
        // Undeclared exception!
        try {
            watchManager0.triggerWatch("M52p/'J.YZ'", watcher_Event_EventType0, (-582L), (List<ACL>) linkedList0);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.zookeeper.server.watch.WatchManager", e);
        }
    }

    @Test(timeout = 4000)
    public void test19()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        watchManager0.addWatch("M2p/'J.YZ'", (Watcher) null);
        LinkedList<ACL> linkedList0 = new LinkedList<ACL>();
        Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.None;
        HashSet<Watcher> hashSet0 = new HashSet<Watcher>();
        hashSet0.add((Watcher) null);
        WatcherOrBitSet watcherOrBitSet0 = new WatcherOrBitSet(hashSet0);
        WatcherOrBitSet watcherOrBitSet1 = watchManager0.triggerWatch("M2p/'J.YZ'", watcher_Event_EventType0, 64L, (List<ACL>) linkedList0, watcherOrBitSet0);
        assertNotSame(watcherOrBitSet0, watcherOrBitSet1);
    }

    @Test(timeout = 4000)
    public void test20()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT;
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        watchManager0.addWatch("9M52p/'J.YZ'", (Watcher) dumbWatcher0, watcherMode0);
        watchManager0.addWatch("9M52p/'J.YZ'", (Watcher) dumbWatcher0);
        LinkedList<ACL> linkedList0 = new LinkedList<ACL>();
        Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.NodeDeleted;
        WatcherOrBitSet watcherOrBitSet0 = watchManager0.triggerWatch("9M52p/'J.YZ'", watcher_Event_EventType0, (-2678L), (List<ACL>) linkedList0);
        assertEquals(1, watcherOrBitSet0.size());
    }

    @Test(timeout = 4000)
    public void test21()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        watchManager0.addWatch("=M)2p/2J.PZ'", (Watcher) null);
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        watchManager0.addWatch("=M)2p/2J.PZ'", (Watcher) dumbWatcher0);
        watchManager0.removeWatcher((Watcher) dumbWatcher0);
        assertEquals(0L, dumbWatcher0.getOutstandingRequests());
    }

    @Test(timeout = 4000)
    public void test22()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        watchManager0.removeWatcher((Watcher) null);
    }

    @Test(timeout = 4000)
    public void test23()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
        watchManager0.addWatch("org.apache.zoo_eeper.server.watch.WatchMa1ager", (Watcher) null, watcherMode0);
        watchManager0.removeWatcher((Watcher) null);
    }

    @Test(timeout = 4000)
    public void test24()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
        boolean boolean0 = watchManager0.addWatch("Td<L,uJSFH_t>Ak}#4", (Watcher) null, watcherMode0);
        boolean boolean1 = watchManager0.addWatch("Td<L,uJSFH_t>Ak}#4", (Watcher) null, watcherMode0);
        assertFalse(boolean1 == boolean0);
        assertFalse(boolean1);
    }

    @Test(timeout = 4000)
    public void test25()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        dumbWatcher0.setStale();
        boolean boolean0 = watchManager0.addWatch("", (Watcher) dumbWatcher0);
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test26()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        boolean boolean0 = watchManager0.addWatch("E@gTU jjTX\"Nli1", (Watcher) null);
        assertTrue(boolean0);

        int int0 = watchManager0.size();
        assertEquals(1, int0);
    }

    @Test(timeout = 4000)
    public void test27()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        boolean boolean0 = watchManager0.removeWatcher("=M)2p/2J.PZ'", (Watcher) null);
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test28()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        WatcherMode watcherMode0 = WatcherMode.STANDARD;
        DumbWatcher dumbWatcher0 = new DumbWatcher(1048576L);
        watchManager0.addWatch("org.apache.zoo_eeper.server.watch.WatchMa1ager", (Watcher) dumbWatcher0, watcherMode0);
        CharArrayWriter charArrayWriter0 = new CharArrayWriter(3);
        PrintWriter printWriter0 = new PrintWriter(charArrayWriter0, false);
        watchManager0.dumpWatches(printWriter0, false);
        assertEquals("0x100000\r\n\torg.apache.zoo_eeper.server.watch.WatchMa1ager\r\n", charArrayWriter0.toString());
        assertEquals(59, charArrayWriter0.size());
    }

    @Test(timeout = 4000)
    public void test29()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        LinkedList<ACL> linkedList0 = new LinkedList<ACL>();
        Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.NodeDeleted;
        WatcherOrBitSet watcherOrBitSet0 = watchManager0.triggerWatch("M52p/'J.YZ'", watcher_Event_EventType0, (-2300L), (List<ACL>) linkedList0);
        assertNull(watcherOrBitSet0);
    }

    @Test(timeout = 4000)
    public void test30()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        Map<Watcher, Map<String, WatchStats>> map0 = watchManager0.getWatch2Paths();
        assertTrue(map0.isEmpty());
    }

    @Test(timeout = 4000)
    public void test31()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        watchManager0.addWatch("M2p/'J.YZ'", (Watcher) null);
        LinkedList<ACL> linkedList0 = new LinkedList<ACL>();
        Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.NodeCreated;
        HashSet<Watcher> hashSet0 = new HashSet<Watcher>();
        WatcherOrBitSet watcherOrBitSet0 = new WatcherOrBitSet(hashSet0);
        // Undeclared exception!
        try {
            watchManager0.triggerWatch("M2p/'J.YZ'", watcher_Event_EventType0, 64L, (List<ACL>) linkedList0, watcherOrBitSet0);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.zookeeper.server.watch.WatchManager", e);
        }
    }

    @Test(timeout = 4000)
    public void test32()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        watchManager0.shutdown();
    }

    @Test(timeout = 4000)
    public void test33()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        boolean boolean0 = watchManager0.containsWatcher("FIPS mode is OFF: creating ZKTrustManaer", (Watcher) null);
        assertFalse(boolean0);
    }
}