/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sat Aug 01 15:22:50 GMT 2026
 */

package org.apache.zookeeper.server.snapshotcomparer.variant_c2.evosuite.snapshotcomparerbranch;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;

@EvoSuiteClassExclude
public class SnapshotComparer_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() {
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.zookeeper.server.SnapshotComparer";
    org.evosuite.runtime.GuiSupport.initialize();
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100;
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000;
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true;
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED;
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT();
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime();
  }

  @AfterClass
  public static void clearEvoSuiteFramework(){
    Sandbox.resetDefaultSecurityManager();
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
  }

  @Before
  public void initTestCase(){
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler();
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode();
    setSystemProperties();
    org.evosuite.runtime.GuiSupport.setHeadless();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime();
    org.evosuite.runtime.agent.InstrumentingAgent.activate();
  }

  @After
  public void doneWithTestCase(){
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks();
    org.evosuite.runtime.classhandling.JDKClassResetter.reset();
    resetClasses();
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode();
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate();
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode();
  }

  public static void setSystemProperties() {

    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
    java.lang.System.setProperty("user.dir", "C:\\Users\\casol\\Desktop\\zookeeper\\zookeeper-server");
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(SnapshotComparer_ESTest_scaffolding.class.getClassLoader() ,
            "org.apache.zookeeper.server.SnapshotComparer$TreeInfo",
            "org.apache.zookeeper.util.ServiceUtils",
            "org.apache.zookeeper.server.SnapshotComparer",
            "org.apache.commons.cli.UnrecognizedOptionException",
            "org.apache.commons.cli.CommandLineParser",
            "org.apache.jute.InputArchive",
            "org.apache.commons.cli.Options",
            "org.apache.commons.cli.Option$Builder",
            "org.apache.commons.cli.MissingOptionException",
            "org.apache.commons.cli.HelpFormatter",
            "org.apache.zookeeper.server.ExitCode",
            "org.apache.commons.cli.DefaultParser",
            "org.apache.commons.cli.AmbiguousOptionException",
            "org.apache.commons.cli.HelpFormatter$OptionComparator",
            "org.apache.commons.cli.ParseException",
            "org.apache.commons.cli.OptionValidator",
            "org.apache.zookeeper.server.DataTree",
            "org.apache.zookeeper.server.SnapshotComparer$TreeInfo$TreeNode",
            "org.apache.commons.cli.CommandLine",
            "org.apache.commons.cli.Option",
            "org.apache.commons.cli.MissingArgumentException",
            "org.apache.commons.cli.Util"
    );
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(SnapshotComparer_ESTest_scaffolding.class.getClassLoader());

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
            "org.apache.zookeeper.server.SnapshotComparer",
            "org.apache.zookeeper.server.SnapshotComparer$TreeInfo",
            "org.apache.zookeeper.server.SnapshotComparer$TreeInfo$TreeNode",
            "org.apache.zookeeper.server.SnapshotComparer$TreeInfo$TreeNode$AlphabeticComparator",
            "org.apache.zookeeper.server.ExitCode",
            "org.apache.zookeeper.util.ServiceUtils",
            "org.apache.zookeeper.server.persistence.SnapStream$StreamMode",
            "org.apache.zookeeper.server.persistence.SnapStream",
            "org.apache.zookeeper.server.persistence.SnapStream$1",
            "org.apache.jute.BinaryInputArchive",
            "org.apache.zookeeper.server.persistence.FileSnap",
            "org.apache.zookeeper.server.util.SerializeUtils",
            "org.apache.zookeeper.server.ZooTrace",
            "org.apache.commons.cli.Options",
            "org.apache.commons.cli.Option",
            "org.apache.commons.cli.Option$Builder",
            "org.apache.commons.cli.OptionValidator",
            "org.apache.commons.cli.DefaultParser",
            "org.apache.commons.cli.CommandLine",
            "org.apache.commons.cli.ParseException",
            "org.apache.commons.cli.MissingOptionException",
            "org.apache.commons.cli.HelpFormatter",
            "org.apache.commons.cli.HelpFormatter$OptionComparator",
            "org.apache.commons.cli.Util",
            "org.apache.commons.cli.UnrecognizedOptionException"
    );
  }
}
