/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 30 17:33:18 GMT 2026
 */

package org.apache.zookeeper.server;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.zookeeper.server.SnapshotComparerTestFacade;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SnapshotComparerTestFacade_ESTest extends SnapshotComparerTestFacade_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      boolean boolean0 = SnapshotComparerTestFacade.gzSnapshotIsSupported();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("src\\test\\resources\\data\\comparer\\right_plus_1.snap");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "e-S");
      EvoSuiteFile evoSuiteFile1 = new EvoSuiteFile("src\\test\\resources\\data\\comparer\\right_mixed.snap");
      FileSystemHandling.createFolder(evoSuiteFile1);
      EvoSuiteFile evoSuiteFile2 = new EvoSuiteFile("src\\test\\resources\\data\\comparer\\left_mixed.snap");
      FileSystemHandling.appendLineToFile(evoSuiteFile2, "e-S");
      EvoSuiteFile evoSuiteFile3 = new EvoSuiteFile("src\\test\\resources\\data\\comparer\\left.snap");
      FileSystemHandling.appendLineToFile(evoSuiteFile3, "e-S");
      EvoSuiteFile evoSuiteFile4 = new EvoSuiteFile("src\\test\\resources\\data\\comparer\\right_identical.snap");
      FileSystemHandling.appendLineToFile(evoSuiteFile4, "e-S");
      boolean boolean0 = SnapshotComparerTestFacade.requiredCoreAssetsExist();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("src\\test\\resources\\data\\comparer\\right_plus_1.snap");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "e-S");
      EvoSuiteFile evoSuiteFile1 = new EvoSuiteFile("src\\test\\resources\\data\\comparer\\left_mixed.snap");
      FileSystemHandling.appendLineToFile(evoSuiteFile1, "e-S");
      EvoSuiteFile evoSuiteFile2 = new EvoSuiteFile("src\\test\\resources\\data\\comparer\\left.snap");
      FileSystemHandling.appendLineToFile(evoSuiteFile2, "e-S");
      EvoSuiteFile evoSuiteFile3 = new EvoSuiteFile("src\\test\\resources\\data\\comparer\\right_identical.snap");
      FileSystemHandling.appendLineToFile(evoSuiteFile3, "e-S");
      boolean boolean0 = SnapshotComparerTestFacade.requiredCoreAssetsExist();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("src\\test\\resources\\data\\comparer\\right_plus_1.snap");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "e-S");
      EvoSuiteFile evoSuiteFile1 = new EvoSuiteFile("src\\test\\resources\\data\\comparer\\left.snap");
      FileSystemHandling.appendLineToFile(evoSuiteFile1, "e-S");
      EvoSuiteFile evoSuiteFile2 = new EvoSuiteFile("src\\test\\resources\\data\\comparer\\right_identical.snap");
      FileSystemHandling.appendLineToFile(evoSuiteFile2, "e-S");
      boolean boolean0 = SnapshotComparerTestFacade.requiredCoreAssetsExist();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("src\\test\\resources\\data\\comparer\\right_plus_1.snap");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "e-S");
      EvoSuiteFile evoSuiteFile1 = new EvoSuiteFile("src\\test\\resources\\data\\comparer\\left.snap");
      FileSystemHandling.appendLineToFile(evoSuiteFile1, "e-S");
      boolean boolean0 = SnapshotComparerTestFacade.requiredCoreAssetsExist();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("src\\test\\resources\\data\\comparer\\left.snap");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "e-S");
      boolean boolean0 = SnapshotComparerTestFacade.requiredCoreAssetsExist();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      boolean boolean0 = SnapshotComparerTestFacade.requiredCoreAssetsExist();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      boolean boolean0 = SnapshotComparerTestFacade.gzAssetExists();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      try { 
        SnapshotComparerTestFacade.duplicateLeftFlagTerminatesOrRunsDeterministically();
        fail("Expecting exception: SecurityException");
      
      } catch(SecurityException e) {
         //
         // Permission Denied
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("src\\test\\resources\\data\\comparer\\right_plus_1.gz");
      FileSystemHandling.createFolder(evoSuiteFile0);
      try { 
        SnapshotComparerTestFacade.gzSnapshotIsSupported();
        fail("Expecting exception: SecurityException");
      
      } catch(SecurityException e) {
         //
         // Permission Denied
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }
}
