/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sat Aug 01 15:27:06 GMT 2026
 */

package org.apache.zookeeper.server.snapshotcomparer.evosuite.snapshotcomparerfacadebranch;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class SnapshotComparerTestFacade_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() {
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.zookeeper.server.SnapshotComparerTestFacade";
    org.evosuite.runtime.GuiSupport.initialize();
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100;
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000;
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true;
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED;
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT();
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime();
  }

  @AfterClass
  public static void clearEvoSuiteFramework(){
    Sandbox.resetDefaultSecurityManager();
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
  }

  @Before
  public void initTestCase(){
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler();
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode();
    setSystemProperties();
    org.evosuite.runtime.GuiSupport.setHeadless();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime();
    org.evosuite.runtime.agent.InstrumentingAgent.activate();
  }

  @After
  public void doneWithTestCase(){
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks();
    org.evosuite.runtime.classhandling.JDKClassResetter.reset();
    resetClasses();
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode();
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate();
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode();
  }

  public static void setSystemProperties() {

    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\casol\\AppData\\Local\\Temp\\");
    java.lang.System.setProperty("user.name", "casol");
    java.lang.System.setProperty("user.home", "C:\\Users\\casol");
    java.lang.System.setProperty("user.dir", "C:\\Users\\casol\\Desktop\\zookeeper\\zookeeper-server");
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(SnapshotComparerTestFacade_ESTest_scaffolding.class.getClassLoader() ,
            "org.apache.zookeeper.server.EphemeralType$1",
            "org.apache.zookeeper.server.ServerStats$Provider",
            "org.apache.zookeeper.util.ServiceUtils",
            "org.apache.zookeeper.metrics.Counter",
            "org.apache.zookeeper.server.util.AdHash",
            "org.apache.zookeeper.metrics.impl.NullMetricsProvider$NullCounterSet",
            "org.apache.jute.InputArchive",
            "org.apache.zookeeper.KeeperException$NoAuthException",
            "org.apache.zookeeper.metrics.CounterSet",
            "com.codahale.metrics.Reservoir",
            "org.apache.zookeeper.server.watch.IWatchManager",
            "org.apache.commons.cli.AmbiguousOptionException",
            "org.apache.zookeeper.server.metric.SimpleCounter",
            "org.apache.zookeeper.server.SessionTracker",
            "org.apache.zookeeper.server.persistence.SnapStream",
            "org.apache.zookeeper.server.RequestRecord",
            "org.apache.zookeeper.server.RequestProcessor",
            "org.apache.zookeeper.proto.ConnectRequest",
            "org.apache.zookeeper.common.PathTrie$TrieNode",
            "org.apache.zookeeper.server.metric.AvgMinMaxPercentileCounter",
            "org.apache.zookeeper.server.DataTree$ProcessTxnResult",
            "org.apache.zookeeper.server.ServerStats",
            "org.apache.commons.cli.UnrecognizedOptionException",
            "org.apache.zookeeper.common.PathTrie",
            "org.apache.zookeeper.ZookeeperBanner",
            "com.codahale.metrics.Metric",
            "org.apache.jute.Record",
            "org.apache.zookeeper.server.watch.WatchManager",
            "org.apache.zookeeper.server.SessionTracker$SessionExpirer",
            "org.apache.commons.cli.Option$1",
            "com.codahale.metrics.Sampling",
            "org.apache.zookeeper.server.ServerWatcher",
            "org.apache.zookeeper.common.AtomicFileOutputStream",
            "org.apache.jute.BinaryInputArchive$BinaryIndex",
            "org.apache.zookeeper.server.metric.AvgMinMaxPercentileCounterSet",
            "org.apache.zookeeper.server.metric.Metric",
            "org.apache.commons.cli.Util",
            "org.apache.zookeeper.KeeperException$InvalidACLException",
            "org.apache.zookeeper.server.metric.AvgMinMaxCounterSet",
            "org.apache.zookeeper.server.RateLogger",
            "org.apache.zookeeper.server.ZKDatabase",
            "org.apache.zookeeper.server.util.RequestPathMetricsCollector",
            "org.apache.zookeeper.server.ServerCnxnFactory",
            "org.apache.zookeeper.server.NodeHashMapImpl",
            "org.apache.commons.cli.HelpFormatter",
            "org.apache.zookeeper.metrics.impl.NullMetricsProvider$NullMetricsContext",
            "org.apache.zookeeper.server.ResponseCache",
            "org.apache.zookeeper.jmx.ZKMBeanInfo",
            "org.xerial.snappy.SnappyInputStream",
            "org.xerial.snappy.SnappyOutputStream",
            "org.apache.zookeeper.metrics.impl.DefaultMetricsProvider",
            "org.apache.zookeeper.server.persistence.FileTxnSnapLog",
            "org.apache.zookeeper.server.ServerCnxn$CloseRequestException",
            "org.apache.zookeeper.server.ServerMetrics",
            "org.apache.zookeeper.server.ZooKeeperServer$State",
            "org.apache.zookeeper.data.StatPersisted",
            "org.apache.jute.OutputArchive",
            "org.apache.zookeeper.server.watch.WatchManagerFactory",
            "org.apache.zookeeper.server.SnapshotComparer$TreeInfo$TreeNode",
            "org.apache.zookeeper.server.persistence.SnapStream$1",
            "org.apache.zookeeper.server.util.SerializeUtils",
            "org.apache.zookeeper.Version",
            "org.apache.zookeeper.server.RequestThrottler",
            "org.apache.commons.cli.Option",
            "org.apache.zookeeper.metrics.MetricsContext",
            "org.apache.zookeeper.Watcher",
            "org.apache.zookeeper.server.EphemeralType",
            "org.apache.zookeeper.txn.TxnHeader",
            "org.apache.commons.cli.MissingOptionException",
            "org.apache.commons.cli.TypeHandler",
            "org.apache.zookeeper.Environment$Entry",
            "org.apache.zookeeper.server.ZooKeeperServer",
            "org.apache.zookeeper.server.persistence.SnapShot",
            "org.apache.zookeeper.data.Id",
            "org.apache.zookeeper.server.DataTree",
            "org.apache.commons.cli.OptionGroup",
            "org.apache.zookeeper.server.Stats",
            "org.apache.zookeeper.server.ReferenceCountedACLCache$AtomicLongWithEquals",
            "org.apache.zookeeper.server.ReferenceCountedACLCache",
            "org.apache.commons.cli.MissingArgumentException",
            "org.apache.zookeeper.metrics.impl.NullMetricsProvider",
            "com.codahale.metrics.UniformSnapshot",
            "org.apache.zookeeper.server.DigestCalculator",
            "org.apache.zookeeper.metrics.impl.DefaultMetricsProvider$DefaultMetricsContext",
            "org.apache.zookeeper.data.Stat",
            "org.apache.zookeeper.server.ZooKeeperServerShutdownHandler",
            "org.apache.zookeeper.metrics.SummarySet",
            "org.apache.zookeeper.KeeperException$NoNodeException",
            "org.apache.zookeeper.metrics.Summary",
            "org.apache.commons.cli.DefaultParser",
            "com.codahale.metrics.Counting",
            "org.apache.zookeeper.KeeperException$BadArgumentsException",
            "org.apache.zookeeper.server.BlueThrottle",
            "org.apache.zookeeper.server.metric.SimpleCounterSet",
            "org.apache.zookeeper.server.ServerCnxn",
            "org.apache.zookeeper.server.DataNode",
            "org.apache.zookeeper.server.ClientCnxnLimitException",
            "org.apache.zookeeper.Environment",
            "org.apache.zookeeper.server.persistence.SnapStream$StreamMode",
            "org.apache.zookeeper.server.SessionTracker$Session",
            "org.apache.zookeeper.KeeperException$QuotaExceededException",
            "org.apache.zookeeper.server.ZooKeeperThread",
            "com.codahale.metrics.Snapshot",
            "org.apache.zookeeper.server.Request",
            "org.apache.zookeeper.proto.RequestHeader",
            "org.apache.commons.cli.ParseException",
            "org.apache.zookeeper.version.Info",
            "org.apache.zookeeper.metrics.impl.NullMetricsProvider$NullCounter",
            "org.apache.zookeeper.server.ZooKeeperServer$MissingSessionException",
            "org.apache.zookeeper.server.persistence.FileSnap",
            "org.apache.zookeeper.metrics.impl.NullMetricsProvider$NullSummarySet",
            "org.apache.jute.Index",
            "org.apache.zookeeper.server.ZooKeeperServerConf",
            "org.apache.commons.cli.PatternOptionBuilder",
            "com.codahale.metrics.Histogram",
            "org.apache.zookeeper.server.SnapshotComparer$TreeInfo$TreeNode$AlphabeticComparator",
            "org.apache.zookeeper.metrics.MetricsProvider",
            "org.apache.commons.cli.Options",
            "org.apache.zookeeper.data.ACL",
            "org.apache.zookeeper.txn.TxnDigest",
            "org.apache.zookeeper.metrics.MetricsContext$DetailLevel",
            "org.apache.zookeeper.server.ZooKeeperCriticalThread",
            "org.apache.zookeeper.server.SnapshotComparerTestFacade$RunResult",
            "org.apache.commons.cli.HelpFormatter$OptionComparator",
            "org.apache.commons.cli.OptionValidator",
            "org.apache.zookeeper.server.ZooKeeperServerListener",
            "org.apache.commons.cli.CommandLine",
            "org.apache.zookeeper.server.metric.AvgMinMaxPercentileCounter$ResettableUniformReservoir",
            "org.apache.zookeeper.server.RequestProcessor$RequestProcessorException",
            "org.apache.zookeeper.server.SnapshotComparer$TreeInfo",
            "org.apache.zookeeper.server.SnapshotComparer",
            "org.apache.zookeeper.KeeperException",
            "org.apache.commons.cli.CommandLineParser",
            "org.apache.zookeeper.server.persistence.FileHeader",
            "org.apache.zookeeper.server.metric.AvgMinMaxCounter",
            "org.apache.commons.cli.Option$Builder",
            "org.apache.zookeeper.server.SnapshotComparerTestFacade$ExitException",
            "org.apache.zookeeper.server.ExitCode",
            "org.apache.zookeeper.KeeperException$SessionExpiredException",
            "org.apache.jute.BinaryInputArchive",
            "org.apache.zookeeper.metrics.impl.NullMetricsProvider$NullSummary",
            "org.apache.zookeeper.KeeperException$NodeExistsException",
            "org.apache.zookeeper.common.PathUtils",
            "org.apache.zookeeper.server.SnapshotComparerTestFacade",
            "org.apache.zookeeper.ZooDefs$Ids",
            "org.apache.zookeeper.server.NodeHashMap"
    );
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(SnapshotComparerTestFacade_ESTest_scaffolding.class.getClassLoader());

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
            "org.apache.zookeeper.server.SnapshotComparerTestFacade",
            "org.apache.zookeeper.server.SnapshotComparerTestFacade$RunResult",
            "org.apache.zookeeper.server.SnapshotComparerTestFacade$ExitException",
            "org.apache.zookeeper.util.ServiceUtils",
            "org.apache.zookeeper.server.SnapshotComparer",
            "org.apache.commons.cli.Options",
            "org.apache.commons.cli.Option",
            "org.apache.commons.cli.Option$Builder",
            "org.apache.commons.cli.OptionValidator",
            "org.apache.commons.cli.DefaultParser",
            "org.apache.commons.cli.CommandLine",
            "org.apache.commons.cli.Util",
            "org.apache.commons.cli.ParseException",
            "org.apache.commons.cli.MissingOptionException",
            "org.apache.commons.cli.HelpFormatter",
            "org.apache.commons.cli.HelpFormatter$OptionComparator",
            "org.apache.zookeeper.server.ExitCode",
            "org.apache.commons.cli.TypeHandler",
            "org.apache.commons.cli.PatternOptionBuilder",
            "org.apache.zookeeper.server.SnapshotComparer$TreeInfo",
            "org.apache.zookeeper.server.DataTree",
            "org.apache.zookeeper.server.DigestCalculator",
            "org.apache.zookeeper.server.RateLogger",
            "org.apache.zookeeper.common.PathTrie",
            "org.apache.zookeeper.common.PathTrie$TrieNode",
            "org.apache.zookeeper.server.ReferenceCountedACLCache",
            "org.apache.zookeeper.server.DataNode",
            "org.apache.zookeeper.data.StatPersisted",
            "org.apache.zookeeper.server.NodeHashMapImpl",
            "org.apache.zookeeper.server.util.AdHash",
            "org.apache.zookeeper.ZookeeperBanner",
            "org.apache.zookeeper.Environment",
            "org.apache.zookeeper.Version",
            "org.apache.zookeeper.version.Info",
            "org.apache.zookeeper.Environment$Entry",
            "org.apache.zookeeper.server.ZooKeeperServer",
            "org.apache.zookeeper.data.Id",
            "org.apache.zookeeper.data.ACL",
            "org.apache.zookeeper.ZooDefs$Ids",
            "org.apache.zookeeper.data.Stat",
            "org.apache.zookeeper.server.ReferenceCountedACLCache$AtomicLongWithEquals",
            "org.apache.zookeeper.server.EphemeralType",
            "org.apache.zookeeper.server.watch.WatchManagerFactory",
            "org.apache.zookeeper.server.watch.WatchManager",
            "org.apache.zookeeper.server.persistence.SnapStream$StreamMode",
            "org.apache.zookeeper.server.persistence.SnapStream",
            "org.apache.zookeeper.server.persistence.SnapStream$1",
            "org.apache.jute.BinaryInputArchive",
            "org.apache.zookeeper.server.persistence.FileSnap",
            "org.apache.zookeeper.server.persistence.FileHeader",
            "org.apache.zookeeper.server.util.SerializeUtils",
            "org.apache.jute.BinaryInputArchive$BinaryIndex",
            "org.apache.zookeeper.server.SnapshotComparer$TreeInfo$TreeNode",
            "org.apache.zookeeper.common.PathUtils",
            "org.apache.zookeeper.metrics.impl.NullMetricsProvider",
            "org.apache.zookeeper.metrics.impl.NullMetricsProvider$NullMetricsContext",
            "org.apache.zookeeper.metrics.MetricsContext$DetailLevel",
            "org.apache.zookeeper.metrics.impl.NullMetricsProvider$NullSummary",
            "org.apache.zookeeper.metrics.impl.NullMetricsProvider$NullCounter",
            "org.apache.zookeeper.metrics.impl.NullMetricsProvider$NullSummarySet",
            "org.apache.zookeeper.metrics.impl.NullMetricsProvider$NullCounterSet",
            "org.apache.zookeeper.metrics.impl.DefaultMetricsProvider",
            "org.apache.zookeeper.metrics.impl.DefaultMetricsProvider$DefaultMetricsContext",
            "org.apache.zookeeper.server.metric.Metric",
            "org.apache.zookeeper.server.metric.AvgMinMaxCounter",
            "org.apache.zookeeper.server.metric.SimpleCounter",
            "org.apache.zookeeper.server.metric.AvgMinMaxPercentileCounter",
            "org.apache.zookeeper.server.metric.AvgMinMaxPercentileCounter$ResettableUniformReservoir",
            "com.codahale.metrics.Histogram",
            "org.apache.zookeeper.server.metric.AvgMinMaxCounterSet",
            "org.apache.zookeeper.server.metric.AvgMinMaxPercentileCounterSet",
            "org.apache.zookeeper.server.metric.SimpleCounterSet",
            "org.apache.zookeeper.server.ServerMetrics",
            "org.apache.zookeeper.server.SnapshotComparer$TreeInfo$TreeNode$AlphabeticComparator",
            "org.apache.commons.cli.MissingArgumentException"
    );
  }
}
