/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 01 15:20:54 GMT 2026
 */

package org.apache.zookeeper.server.snapshotcomparer.evosuite.snapshotcomparerbranch;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.NoSuchElementException;
import org.apache.zookeeper.server.SnapshotComparerTestFacade;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class SnapshotComparerTestFacade_ESTest extends SnapshotComparerTestFacade_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test00()  throws Throwable  {
        boolean boolean0 = SnapshotComparerTestFacade.interactiveInvalidAbsolutePathPrintsError();
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test01()  throws Throwable  {
        boolean boolean0 = SnapshotComparerTestFacade.interactiveDepthBelowMinimumPrintsRangeError();
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test02()  throws Throwable  {
        boolean boolean0 = SnapshotComparerTestFacade.nodeThresholdAboveDeltaFiltersParentDelta();
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test03()  throws Throwable  {
        boolean boolean0 = SnapshotComparerTestFacade.nodeThresholdEqualToDeltaFiltersParentDelta();
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test04()  throws Throwable  {
        boolean boolean0 = SnapshotComparerTestFacade.nodeThresholdBelowDeltaReportsParentDelta();
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test05()  throws Throwable  {
        boolean boolean0 = SnapshotComparerTestFacade.byteThresholdAboveDeltaFiltersPayloadDelta();
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test06()  throws Throwable  {
        boolean boolean0 = SnapshotComparerTestFacade.byteThresholdEqualToDeltaFiltersPayloadDelta();
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test07()  throws Throwable  {
        boolean boolean0 = SnapshotComparerTestFacade.byteThresholdBelowDeltaReportsPayloadDelta();
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test08()  throws Throwable  {
        boolean boolean0 = SnapshotComparerTestFacade.mixedDifferencesAreReported();
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test09()  throws Throwable  {
        boolean boolean0 = SnapshotComparerTestFacade.pathOnlyInLeftIsReported();
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test10()  throws Throwable  {
        boolean boolean0 = SnapshotComparerTestFacade.pathOnlyInRightIsReported();
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test11()  throws Throwable  {
        boolean boolean0 = SnapshotComparerTestFacade.samePathsDifferentPayloadIsReported();
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test12()  throws Throwable  {
        boolean boolean0 = SnapshotComparerTestFacade.differentFilesSameTreeProducesNoDelta();
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test13()  throws Throwable  {
        boolean boolean0 = SnapshotComparerTestFacade.samePhysicalFileProducesNoDelta();
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test14()  throws Throwable  {
        boolean boolean0 = SnapshotComparerTestFacade.gzSnapshotIsSupported();
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test15()  throws Throwable  {
        boolean boolean0 = SnapshotComparerTestFacade.missingSnapshotFailsLoading();
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test16()  throws Throwable  {
        boolean boolean0 = SnapshotComparerTestFacade.ephemeralNodesAreIgnored();
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test17()  throws Throwable  {
        boolean boolean0 = SnapshotComparerTestFacade.integerOverflowIsRejected();
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test18()  throws Throwable  {
        boolean boolean0 = SnapshotComparerTestFacade.duplicateLeftFlagHasControlledBehavior();
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test19()  throws Throwable  {
        try {
            SnapshotComparerTestFacade.missingNodeThresholdIsRejected();
            fail("Expecting exception: NoSuchElementException");

        } catch(NoSuchElementException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("java.util.LinkedList", e);
        }
    }

    @Test(timeout = 4000)
    public void test20()  throws Throwable  {
        boolean boolean0 = SnapshotComparerTestFacade.compareBaselineFindsRightOnlyNode();
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test21()  throws Throwable  {
        boolean boolean0 = SnapshotComparerTestFacade.compareNominal(0, 0, true);
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test22()  throws Throwable  {
        boolean boolean0 = SnapshotComparerTestFacade.compareNominal(0, 0, false);
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test23()  throws Throwable  {
        try {
            SnapshotComparerTestFacade.flagWithoutArgumentFailsParsing();
            fail("Expecting exception: NoSuchElementException");

        } catch(NoSuchElementException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("java.util.LinkedList", e);
        }
    }

    @Test(timeout = 4000)
    public void test24()  throws Throwable  {
        boolean boolean0 = SnapshotComparerTestFacade.compareMixedWithThresholds((-969), (-969));
        assertTrue(boolean0);
    }
}
