/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 01 15:47:42 GMT 2026
 */

package org.apache.zookeeper.server.watch.watchmanager.variant_c3.evosuite;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.CharArrayWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import org.apache.zookeeper.Watcher;
import org.apache.zookeeper.data.ACL;
import org.apache.zookeeper.server.DumbWatcher;
import org.apache.zookeeper.server.watch.WatchManager;
import org.apache.zookeeper.server.watch.WatchStats;
import org.apache.zookeeper.server.watch.WatcherMode;
import org.apache.zookeeper.server.watch.WatcherOrBitSet;
import org.apache.zookeeper.server.watch.WatchesPathReport;
import org.apache.zookeeper.server.watch.WatchesReport;
import org.apache.zookeeper.server.watch.WatchesSummary;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class WatchManager_ESTest extends WatchManager_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test00()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        boolean boolean0 = watchManager0.addWatch("", (Watcher) dumbWatcher0);
        assertTrue(boolean0);

        WatchesSummary watchesSummary0 = watchManager0.getWatchesSummary();
        assertEquals(1, watchesSummary0.getTotalWatches());
    }

    @Test(timeout = 4000)
    public void test01()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        watchManager0.addWatch("/GT3;p~5<n0[z:L", (Watcher) dumbWatcher0);
        WatchesReport watchesReport0 = watchManager0.getWatches();
        assertNotNull(watchesReport0);
    }

    @Test(timeout = 4000)
    public void test02()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        boolean boolean0 = watchManager0.addWatch(" paths\n", (Watcher) dumbWatcher0);
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
        boolean boolean1 = watchManager0.removeWatcher(" paths\n", (Watcher) dumbWatcher0, watcherMode0);
        assertFalse(boolean1 == boolean0);
        assertFalse(boolean1);
    }

    @Test(timeout = 4000)
    public void test03()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        boolean boolean0 = watchManager0.addWatch("zookeeper.sasl.serverconfig", (Watcher) dumbWatcher0);
        assertTrue(boolean0);

        boolean boolean1 = watchManager0.removeWatcher("zookeeper.sasl.serverconfig", (Watcher) dumbWatcher0);
        assertTrue(boolean1);
    }

    @Test(timeout = 4000)
    public void test04()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        boolean boolean0 = watchManager0.addWatch("", (Watcher) dumbWatcher0);
        DumbWatcher dumbWatcher1 = new DumbWatcher();
        watchManager0.addWatch("Vq1;KE_]-?~\"s^<~/}w", (Watcher) dumbWatcher1);
        WatcherMode watcherMode0 = WatcherMode.STANDARD;
        boolean boolean1 = watchManager0.removeWatcher("", (Watcher) dumbWatcher1, watcherMode0);
        assertFalse(boolean1 == boolean0);
        assertFalse(boolean1);
    }

    @Test(timeout = 4000)
    public void test05()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        boolean boolean0 = watchManager0.addWatch("/GT3;p~5<n0[z:L", (Watcher) dumbWatcher0);
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
        boolean boolean1 = watchManager0.removeWatcher("0x{} `bLen {}", (Watcher) dumbWatcher0, watcherMode0);
        assertFalse(boolean1 == boolean0);
        assertFalse(boolean1);
    }

    @Test(timeout = 4000)
    public void test06()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        watchManager0.addWatch((String) null, (Watcher) dumbWatcher0);
        WatcherMode watcherMode0 = WatcherMode.STANDARD;
        boolean boolean0 = watchManager0.addWatch("", (Watcher) dumbWatcher0, watcherMode0);
        assertTrue(boolean0);

        boolean boolean1 = watchManager0.removeWatcher("", (Watcher) dumbWatcher0, watcherMode0);
        assertTrue(boolean1);
    }

    @Test(timeout = 4000)
    public void test07()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
        boolean boolean0 = watchManager0.addWatch("", (Watcher) dumbWatcher0, watcherMode0);
        assertTrue(boolean0);

        boolean boolean1 = watchManager0.containsWatcher("", (Watcher) dumbWatcher0, watcherMode0);
        assertTrue(boolean1);
    }

    @Test(timeout = 4000)
    public void test08()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
        boolean boolean0 = watchManager0.addWatch("", (Watcher) dumbWatcher0, watcherMode0);
        assertTrue(boolean0);

        boolean boolean1 = watchManager0.containsWatcher("", (Watcher) dumbWatcher0);
        assertTrue(boolean1);
    }

    @Test(timeout = 4000)
    public void test09()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        boolean boolean0 = watchManager0.addWatch(" connections watching ", (Watcher) dumbWatcher0);
        boolean boolean1 = watchManager0.containsWatcher("!-3[shc", (Watcher) dumbWatcher0);
        assertFalse(boolean1 == boolean0);
        assertFalse(boolean1);
    }

    @Test(timeout = 4000)
    public void test10()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        boolean boolean0 = watchManager0.addWatch("/GT3;p5~5<n0[ze:L", (Watcher) dumbWatcher0);
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT;
        boolean boolean1 = watchManager0.containsWatcher("/GT3;p5~5<n0[ze:L", (Watcher) dumbWatcher0, watcherMode0);
        assertFalse(boolean1 == boolean0);
        assertFalse(boolean1);
    }

    @Test(timeout = 4000)
    public void test11()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        watchManager0.addWatch("/GT3;p5~5<n0[ze:L", (Watcher) dumbWatcher0);
        // Undeclared exception!
        try {
            watchManager0.dumpWatches((PrintWriter) null, false);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.zookeeper.server.watch.WatchManager", e);
        }
    }

    @Test(timeout = 4000)
    public void test12()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        watchManager0.addWatch("h,+95@WCrlYyn", (Watcher) dumbWatcher0);
        CharArrayWriter charArrayWriter0 = new CharArrayWriter();
        PrintWriter printWriter0 = new PrintWriter(charArrayWriter0, true);
        watchManager0.dumpWatches(printWriter0, true);
        assertEquals("h,+95@WCrlYyn\r\n\t0x0\n", charArrayWriter0.toString());
        assertEquals(20, charArrayWriter0.size());
    }

    @Test(timeout = 4000)
    public void test13()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        watchManager0.dumpWatches((PrintWriter) null, false);
    }

    @Test(timeout = 4000)
    public void test14()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        watchManager0.addWatch("ZH/|Lcgi", (Watcher) dumbWatcher0);
        Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.NodeDeleted;
        LinkedList<ACL> linkedList0 = new LinkedList<ACL>();
        LinkedHashSet<Watcher> linkedHashSet0 = new LinkedHashSet<Watcher>();
        linkedHashSet0.add(dumbWatcher0);
        WatcherOrBitSet watcherOrBitSet0 = new WatcherOrBitSet(linkedHashSet0);
        WatcherOrBitSet watcherOrBitSet1 = watchManager0.triggerWatch("ZH/|Lcgi", watcher_Event_EventType0, 1713L, (List<ACL>) linkedList0, watcherOrBitSet0);
        assertNotSame(watcherOrBitSet0, watcherOrBitSet1);
    }

    @Test(timeout = 4000)
    public void test15()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        LinkedList<ACL> linkedList0 = new LinkedList<ACL>();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        watchManager0.addWatch("ZH/|Lcgi", (Watcher) dumbWatcher0);
        Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.NodeChildrenChanged;
        WatcherOrBitSet watcherOrBitSet0 = watchManager0.triggerWatch("ZH/|Lcgi", watcher_Event_EventType0, (-1367L), (List<ACL>) linkedList0);
        assertEquals(1, watcherOrBitSet0.size());
    }

    @Test(timeout = 4000)
    public void test16()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        LinkedList<ACL> linkedList0 = new LinkedList<ACL>();
        Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.NodeDataChanged;
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        watchManager0.addWatch("f?=B/W]", (Watcher) dumbWatcher0);
        WatcherOrBitSet watcherOrBitSet0 = watchManager0.triggerWatch("f?=B/W]", watcher_Event_EventType0, (-2098L), (List<ACL>) linkedList0);
        assertEquals(1, watcherOrBitSet0.size());
    }

    @Test(timeout = 4000)
    public void test17()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        LinkedList<ACL> linkedList0 = new LinkedList<ACL>();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        watchManager0.addWatch("f?=B/W]", (Watcher) dumbWatcher0);
        Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.NodeCreated;
        WatcherOrBitSet watcherOrBitSet0 = watchManager0.triggerWatch("f?=B/W]", watcher_Event_EventType0, 0L, (List<ACL>) linkedList0);
        assertEquals(1, watcherOrBitSet0.size());
    }

    @Test(timeout = 4000)
    public void test18()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        LinkedList<ACL> linkedList0 = new LinkedList<ACL>();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT;
        watchManager0.addWatch("f?=B/]", (Watcher) dumbWatcher0, watcherMode0);
        WatcherMode watcherMode1 = WatcherMode.STANDARD;
        watchManager0.addWatch("f?=B/]", (Watcher) dumbWatcher0, watcherMode1);
        Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.PersistentWatchRemoved;
        WatcherOrBitSet watcherOrBitSet0 = watchManager0.triggerWatch("f?=B/]", watcher_Event_EventType0, 811L, (List<ACL>) linkedList0);
        assertEquals(1, watcherOrBitSet0.size());
    }

    @Test(timeout = 4000)
    public void test19()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        watchManager0.addWatch("ZH/|Lcgi", (Watcher) dumbWatcher0);
        Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.NodeDeleted;
        LinkedList<ACL> linkedList0 = new LinkedList<ACL>();
        LinkedHashSet<Watcher> linkedHashSet0 = new LinkedHashSet<Watcher>();
        WatcherOrBitSet watcherOrBitSet0 = new WatcherOrBitSet(linkedHashSet0);
        WatcherOrBitSet watcherOrBitSet1 = watchManager0.triggerWatch("ZH/|Lcgi", watcher_Event_EventType0, 1713L, (List<ACL>) linkedList0, watcherOrBitSet0);
        assertEquals(1, watcherOrBitSet1.size());
    }

    @Test(timeout = 4000)
    public void test20()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        LinkedList<ACL> linkedList0 = new LinkedList<ACL>();
        Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.NodeDeleted;
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
        watchManager0.addWatch("ZH/|c#gj", (Watcher) dumbWatcher0, watcherMode0);
        // Undeclared exception!
        try {
            watchManager0.triggerWatch("ZH/|c#gj", watcher_Event_EventType0, (-1074L), (List<ACL>) linkedList0);
            fail("Expecting exception: StringIndexOutOfBoundsException");

        } catch(StringIndexOutOfBoundsException e) {
        }
    }

    @Test(timeout = 4000)
    public void test21()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        watchManager0.removeWatcher((Watcher) dumbWatcher0);
        assertEquals(0L, dumbWatcher0.getSessionId());
    }

    @Test(timeout = 4000)
    public void test22()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
        boolean boolean0 = watchManager0.addWatch("", (Watcher) dumbWatcher0, watcherMode0);
        assertTrue(boolean0);

        boolean boolean1 = watchManager0.removeWatcher("", (Watcher) dumbWatcher0, watcherMode0);
        assertTrue(boolean1);
    }

    @Test(timeout = 4000)
    public void test23()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
        watchManager0.addWatch("", (Watcher) dumbWatcher0);
        boolean boolean0 = watchManager0.addWatch("", (Watcher) dumbWatcher0, watcherMode0);
        assertTrue(boolean0);

        boolean boolean1 = watchManager0.removeWatcher("", (Watcher) dumbWatcher0, watcherMode0);
        assertTrue(boolean1);
    }

    @Test(timeout = 4000)
    public void test24()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        watchManager0.addWatch("", (Watcher) dumbWatcher0);
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT;
        boolean boolean0 = watchManager0.addWatch("", (Watcher) dumbWatcher0, watcherMode0);
        assertTrue(boolean0);

        boolean boolean1 = watchManager0.removeWatcher("", (Watcher) dumbWatcher0, watcherMode0);
        assertTrue(boolean1);
    }

    @Test(timeout = 4000)
    public void test25()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        boolean boolean0 = watchManager0.addWatch(" connections watching ", (Watcher) dumbWatcher0);
        boolean boolean1 = watchManager0.addWatch(" connections watching ", (Watcher) dumbWatcher0);
        assertFalse(boolean1 == boolean0);
        assertFalse(boolean1);
    }

    @Test(timeout = 4000)
    public void test26()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        dumbWatcher0.setStale();
        boolean boolean0 = watchManager0.addWatch("ttl_node_deleted_count", (Watcher) dumbWatcher0);
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test27()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        watchManager0.addWatch("f?=B/W]", (Watcher) null);
        ArrayList<ACL> arrayList0 = new ArrayList<ACL>();
        Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.ChildWatchRemoved;
        // Undeclared exception!
        try {
            watchManager0.triggerWatch("f?=B/W]", watcher_Event_EventType0, 1014L, (List<ACL>) arrayList0);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.zookeeper.server.watch.WatchManager", e);
        }
    }

    @Test(timeout = 4000)
    public void test28()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        boolean boolean0 = watchManager0.addWatch("eFcd", (Watcher) dumbWatcher0);
        assertTrue(boolean0);

        int int0 = watchManager0.size();
        assertEquals(1, int0);
    }

    @Test(timeout = 4000)
    public void test29()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        boolean boolean0 = watchManager0.removeWatcher("zookeeper.sasl.serverconfig", (Watcher) dumbWatcher0);
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test30()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        watchManager0.addWatch("Ignoring addWatch with closed cnxn", (Watcher) dumbWatcher0);
        WatchesPathReport watchesPathReport0 = watchManager0.getWatchesByPath();
        assertNotNull(watchesPathReport0);
    }

    @Test(timeout = 4000)
    public void test31()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        String string0 = watchManager0.toString();
        assertEquals("0 connections watching 0 paths\nTotal watches:0", string0);
    }

    @Test(timeout = 4000)
    public void test32()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        Map<Watcher, Map<String, WatchStats>> map0 = watchManager0.getWatch2Paths();
        assertTrue(map0.isEmpty());
    }

    @Test(timeout = 4000)
    public void test33()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        watchManager0.addWatch("ZH/|Lcgi", (Watcher) dumbWatcher0);
        watchManager0.removeWatcher((Watcher) dumbWatcher0);
        assertNull(dumbWatcher0.getLastOperation());
    }

    @Test(timeout = 4000)
    public void test34()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        watchManager0.shutdown();
    }

    @Test(timeout = 4000)
    public void test35()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.NodeDeleted;
        LinkedList<ACL> linkedList0 = new LinkedList<ACL>();
        LinkedHashSet<Watcher> linkedHashSet0 = new LinkedHashSet<Watcher>();
        WatcherOrBitSet watcherOrBitSet0 = new WatcherOrBitSet(linkedHashSet0);
        WatcherOrBitSet watcherOrBitSet1 = watchManager0.triggerWatch("ZH/|Lcgi", watcher_Event_EventType0, 1713L, (List<ACL>) linkedList0, watcherOrBitSet0);
        assertNull(watcherOrBitSet1);
    }

    @Test(timeout = 4000)
    public void test36()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        boolean boolean0 = watchManager0.containsWatcher("!-3[shc", (Watcher) dumbWatcher0);
        assertFalse(boolean0);
    }
}
