/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 01 15:34:48 GMT 2026
 */

package org.apache.zookeeper.server.snapshotcomparer.variant_c4.evosuite.snapshotcomparerbranch;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.zookeeper.server.SnapshotComparer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class SnapshotComparer_ESTest extends SnapshotComparer_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0()  throws Throwable  {
        // Undeclared exception!
        try {
            SnapshotComparer.main((String[]) null);
            fail("Expecting exception: System.SystemExitException");

        } catch(System.SystemExitException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.evosuite.runtime.System", e);
        }
    }
}
