/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 01 15:39:08 GMT 2026
 */

package org.apache.zookeeper.server.watch;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.CharArrayWriter;
import java.io.PrintWriter;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Stack;
import java.util.Vector;
import org.apache.zookeeper.Watcher;
import org.apache.zookeeper.data.ACL;
import org.apache.zookeeper.server.DumbWatcher;
import org.apache.zookeeper.server.watch.WatchManagerC1_ESTest_scaffolding;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class WatchManagerC1_ESTest extends WatchManagerC1_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test00()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
        watchManager0.addWatch("q6/a5(<v", (Watcher) null, watcherMode0);
        Vector<ACL> vector0 = new Vector<ACL>();
        Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.DataWatchRemoved;
        // Undeclared exception!
        try {
            watchManager0.triggerWatch("q6/a5(<v", watcher_Event_EventType0, (-418L), (List<ACL>) vector0);
            fail("Expecting exception: StringIndexOutOfBoundsException");

        } catch(StringIndexOutOfBoundsException e) {
        }
    }

    @Test(timeout = 4000)
    public void test01()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        WatcherMode watcherMode0 = WatcherMode.STANDARD;
        boolean boolean0 = watchManager0.addWatch("S^gNLa~~K", (Watcher) null, watcherMode0);
        assertTrue(boolean0);

        WatchesSummary watchesSummary0 = watchManager0.getWatchesSummary();
        assertEquals(1, watchesSummary0.getTotalWatches());
    }

    @Test(timeout = 4000)
    public void test02()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        watchManager0.addWatch("Could not deletezcontainer: {}", (Watcher) dumbWatcher0);
        WatchesPathReport watchesPathReport0 = watchManager0.getWatchesByPath();
        assertNotNull(watchesPathReport0);
    }

    @Test(timeout = 4000)
    public void test03()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        boolean boolean0 = watchManager0.addWatch("Could not deletezcontainer: {}", (Watcher) dumbWatcher0);
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT;
        boolean boolean1 = watchManager0.removeWatcher("Could not deletezcontainer: {}", (Watcher) dumbWatcher0, watcherMode0);
        assertFalse(boolean1 == boolean0);
        assertFalse(boolean1);
    }

    @Test(timeout = 4000)
    public void test04()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
        watchManager0.addWatch("6/mk(wv", (Watcher) null, watcherMode0);
        DumbWatcher dumbWatcher0 = new DumbWatcher(348L);
        boolean boolean0 = watchManager0.addWatch((String) null, (Watcher) dumbWatcher0, watcherMode0);
        boolean boolean1 = watchManager0.removeWatcher("6/mk(wv", (Watcher) dumbWatcher0, watcherMode0);
        assertFalse(boolean1 == boolean0);
        assertFalse(boolean1);
    }

    @Test(timeout = 4000)
    public void test05()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        boolean boolean0 = watchManager0.addWatch("not_read_only_client", (Watcher) dumbWatcher0, watcherMode0);
        assertTrue(boolean0);

        boolean boolean1 = watchManager0.removeWatcher("not_read_only_client", (Watcher) dumbWatcher0);
        assertTrue(boolean1);
    }

    @Test(timeout = 4000)
    public void test06()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
        boolean boolean0 = watchManager0.addWatch("", (Watcher) null, watcherMode0);
        assertTrue(boolean0);

        boolean boolean1 = watchManager0.removeWatcher("", (Watcher) null, watcherMode0);
        assertTrue(boolean1);
    }

    @Test(timeout = 4000)
    public void test07()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
        boolean boolean0 = watchManager0.addWatch("6/mk(wv", (Watcher) null, watcherMode0);
        boolean boolean1 = watchManager0.removeWatcher("", (Watcher) null, watcherMode0);
        assertFalse(boolean1 == boolean0);
        assertFalse(boolean1);
    }

    @Test(timeout = 4000)
    public void test08()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        WatcherMode watcherMode0 = WatcherMode.STANDARD;
        watchManager0.addWatch("S^gNLa~~K", (Watcher) null, watcherMode0);
        boolean boolean0 = watchManager0.addWatch("chain", (Watcher) null, watcherMode0);
        assertTrue(boolean0);

        boolean boolean1 = watchManager0.removeWatcher("S^gNLa~~K", (Watcher) null);
        assertTrue(boolean1);
    }

    @Test(timeout = 4000)
    public void test09()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        boolean boolean0 = watchManager0.addWatch("fould not delete container) {}", (Watcher) dumbWatcher0);
        DumbWatcher dumbWatcher1 = new DumbWatcher();
        WatcherMode watcherMode0 = WatcherMode.STANDARD;
        watchManager0.addWatch("nt8SBrn=q2t -x", (Watcher) dumbWatcher1, watcherMode0);
        boolean boolean1 = watchManager0.removeWatcher("fould not delete container) {}", (Watcher) dumbWatcher1);
        assertFalse(boolean1 == boolean0);
        assertFalse(boolean1);
    }

    @Test(timeout = 4000)
    public void test10()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
        boolean boolean0 = watchManager0.addWatch("/9GW \"a/JoIS/:MYZiW", (Watcher) dumbWatcher0);
        boolean boolean1 = watchManager0.containsWatcher("/9GW \"a/JoIS/:MYZiW", (Watcher) dumbWatcher0, watcherMode0);
        assertFalse(boolean1 == boolean0);
        assertFalse(boolean1);
    }

    @Test(timeout = 4000)
    public void test11()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT;
        boolean boolean0 = watchManager0.addWatch("wD38K:[UPF|<bL,|", (Watcher) null, watcherMode0);
        assertTrue(boolean0);

        boolean boolean1 = watchManager0.containsWatcher("wD38K:[UPF|<bL,|", (Watcher) null, watcherMode0);
        assertTrue(boolean1);
    }

    @Test(timeout = 4000)
    public void test12()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        boolean boolean0 = watchManager0.addWatch("org.apache.zookeeper.CreateMode", (Watcher) dumbWatcher0);
        boolean boolean1 = watchManager0.containsWatcher("R~", (Watcher) dumbWatcher0);
        assertFalse(boolean1 == boolean0);
        assertFalse(boolean1);
    }

    @Test(timeout = 4000)
    public void test13()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        boolean boolean0 = watchManager0.addWatch("fould not elete cntainer) {", (Watcher) dumbWatcher0);
        assertTrue(boolean0);

        boolean boolean1 = watchManager0.containsWatcher("fould not elete cntainer) {", (Watcher) dumbWatcher0);
        assertTrue(boolean1);
    }

    @Test(timeout = 4000)
    public void test14()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        WatcherMode watcherMode0 = WatcherMode.STANDARD;
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        watchManager0.addWatch("", (Watcher) dumbWatcher0, watcherMode0);
        CharArrayWriter charArrayWriter0 = new CharArrayWriter(110);
        PrintWriter printWriter0 = new PrintWriter(charArrayWriter0);
        watchManager0.dumpWatches(printWriter0, false);
        assertEquals(8, charArrayWriter0.size());
        assertEquals("0x0\r\n\t\r\n", charArrayWriter0.toString());
    }

    @Test(timeout = 4000)
    public void test15()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        watchManager0.addWatch("/9GW \"a/JoIS/:MYZiW", (Watcher) dumbWatcher0);
        CharArrayWriter charArrayWriter0 = new CharArrayWriter(110);
        PrintWriter printWriter0 = new PrintWriter(charArrayWriter0);
        watchManager0.dumpWatches(printWriter0, true);
        assertEquals("/9GW \"a/JoIS/:MYZiW\r\n\t0x0\n", charArrayWriter0.toString());
        assertEquals(26, charArrayWriter0.size());
    }

    @Test(timeout = 4000)
    public void test16()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher((-889L));
        boolean boolean0 = watchManager0.addWatch("Could not delete container: {}", (Watcher) dumbWatcher0);
        assertTrue(boolean0);

        String string0 = watchManager0.toString();
        assertEquals(" null[0](queued=0,recved=0,sent=0,sid=0xfffffffffffffc87,lop=null,est=1392409281320,to=0,lcxid=0x0,lzxid=0x0,lresp=0,llat=0,minlat=0,avglat=0,maxlat=0)\n\tCould not delete container: {}\n", string0);
    }

    @Test(timeout = 4000)
    public void test17()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        watchManager0.addWatch("/9GW \"a/JoIS/:MYZiW", (Watcher) dumbWatcher0);
        Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.NodeChildrenChanged;
        Vector<ACL> vector0 = new Vector<ACL>();
        HashSet<Watcher> hashSet0 = new HashSet<Watcher>();
        hashSet0.add(dumbWatcher0);
        WatcherOrBitSet watcherOrBitSet0 = new WatcherOrBitSet(hashSet0);
        WatcherOrBitSet watcherOrBitSet1 = watchManager0.triggerWatch("/9GW \"a/JoIS/:MYZiW", watcher_Event_EventType0, 0L, (List<ACL>) vector0, watcherOrBitSet0);
        assertEquals(1, watcherOrBitSet1.size());
    }

    @Test(timeout = 4000)
    public void test18()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        watchManager0.addWatch("q6/a5(<v", (Watcher) null);
        WatcherOrBitSet watcherOrBitSet0 = new WatcherOrBitSet((Set<Watcher>) null);
        Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.NodeCreated;
        // Undeclared exception!
        try {
            watchManager0.triggerWatch("q6/a5(<v", watcher_Event_EventType0, (-1456L), (List<ACL>) null, watcherOrBitSet0);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.zookeeper.server.watch.WatchManager", e);
        }
    }

    @Test(timeout = 4000)
    public void test19()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        watchManager0.addWatch("q/a5(<v", (Watcher) null);
        LinkedList<ACL> linkedList0 = new LinkedList<ACL>();
        Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.PersistentWatchRemoved;
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT;
        watchManager0.addWatch("q/a5(<v", (Watcher) null, watcherMode0);
        // Undeclared exception!
        try {
            watchManager0.triggerWatch("q/a5(<v", watcher_Event_EventType0, 0L, (List<ACL>) linkedList0);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.zookeeper.server.watch.WatchManager", e);
        }
    }

    @Test(timeout = 4000)
    public void test20()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        LinkedList<ACL> linkedList0 = new LinkedList<ACL>();
        DumbWatcher dumbWatcher0 = new DumbWatcher((-3308L));
        watchManager0.addWatch("q/a5(<v", (Watcher) dumbWatcher0);
        Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.NodeChildrenChanged;
        WatcherOrBitSet watcherOrBitSet0 = watchManager0.triggerWatch("q/a5(<v", watcher_Event_EventType0, (-3308L), (List<ACL>) linkedList0);
        assertEquals(1, watcherOrBitSet0.size());
    }

    @Test(timeout = 4000)
    public void test21()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
        watchManager0.addWatch("S=^gLa~K", (Watcher) null, watcherMode0);
        watchManager0.removeWatcher((Watcher) null);
    }

    @Test(timeout = 4000)
    public void test22()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        watchManager0.removeWatcher((Watcher) dumbWatcher0);
        assertEquals(0, dumbWatcher0.getInterestOps());
    }

    @Test(timeout = 4000)
    public void test23()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        watchManager0.addWatch("q/a5(<v", (Watcher) null);
        watchManager0.removeWatcher((Watcher) null);
    }

    @Test(timeout = 4000)
    public void test24()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        WatcherMode watcherMode0 = WatcherMode.PERSISTENT_RECURSIVE;
        watchManager0.addWatch("q6/a5(<v", (Watcher) null, watcherMode0);
        WatcherMode watcherMode1 = WatcherMode.PERSISTENT;
        boolean boolean0 = watchManager0.addWatch("q6/a5(<v", (Watcher) null, watcherMode1);
        assertTrue(boolean0);

        boolean boolean1 = watchManager0.removeWatcher("q6/a5(<v", (Watcher) null, watcherMode1);
        assertTrue(boolean1);
    }

    @Test(timeout = 4000)
    public void test25()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        WatcherMode watcherMode0 = WatcherMode.STANDARD;
        boolean boolean0 = watchManager0.addWatch("Found ", (Watcher) null, watcherMode0);
        boolean boolean1 = watchManager0.addWatch("Found ", (Watcher) null, watcherMode0);
        assertFalse(boolean1 == boolean0);
        assertFalse(boolean1);
    }

    @Test(timeout = 4000)
    public void test26()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        dumbWatcher0.setStale();
        boolean boolean0 = watchManager0.addWatch("q6/a5(<v", (Watcher) dumbWatcher0);
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test27()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        boolean boolean0 = watchManager0.addWatch("fould not elete cntainer) {", (Watcher) dumbWatcher0);
        assertTrue(boolean0);

        int int0 = watchManager0.size();
        assertEquals(1, int0);
    }

    @Test(timeout = 4000)
    public void test28()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        boolean boolean0 = watchManager0.removeWatcher("q6/a5(<v", (Watcher) null);
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test29()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        watchManager0.addWatch("fould not elete cntainer) {", (Watcher) dumbWatcher0);
        WatchesReport watchesReport0 = watchManager0.getWatches();
        assertNotNull(watchesReport0);
    }

    @Test(timeout = 4000)
    public void test30()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        Map<Watcher, Map<String, WatchStats>> map0 = watchManager0.getWatch2Paths();
        assertEquals(0, map0.size());
    }

    @Test(timeout = 4000)
    public void test31()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        watchManager0.shutdown();
    }

    @Test(timeout = 4000)
    public void test32()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        Stack<ACL> stack0 = new Stack<ACL>();
        Watcher.Event.EventType watcher_Event_EventType0 = Watcher.Event.EventType.DataWatchRemoved;
        WatcherOrBitSet watcherOrBitSet0 = watchManager0.triggerWatch("qk/a}}5(}y", watcher_Event_EventType0, (-427L), (List<ACL>) stack0);
        assertNull(watcherOrBitSet0);
    }

    @Test(timeout = 4000)
    public void test33()  throws Throwable  {
        WatchManager watchManager0 = new WatchManager();
        DumbWatcher dumbWatcher0 = new DumbWatcher();
        boolean boolean0 = watchManager0.containsWatcher("fould not elete cntainer) {", (Watcher) dumbWatcher0);
        assertFalse(boolean0);
    }
}
